apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    cluster: cluster-east
    owner: platform-team
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: aggregate-gke-networking-view
rules:
- apiGroups:
  - networking.gke.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
